---
- hosts: es
  tasks:
    - copy:
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        content: |
               127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
               ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
               {% for i in groups.es %}
               {{ hostvars[i].ansible_eth0.ipv4.address }} {{ hostvars[i].ansible_hostname }}
               {% endfor %}
    - name: install es
      dnf:
        name: elasticsearch
        state: present
    - template:
        src: elasticsearch.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0660'
    - service:
        name: elasticsearch
        state: started
        enabled: yes